[versions]
kotlin = "2.2.20"
serialization = "1.9.0"
junit = "5.13.4"
truth = "1.4.5"
guava = "33.5.0-jre"
okio = "3.16.2"

[libraries]
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api" }
google-truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }